# Generated by Django 5.0 on 2023-12-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='appointment date')),
                ('description', models.CharField(max_length=256)),
                ('yearly', models.BooleanField(default=False)),
            ],
        ),
    ]
