# Generated by Django 5.0 on 2024-07-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0003_appointment_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateField(verbose_name='timer last updated')),
                ('count', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=256)),
                ('owner', models.CharField(max_length=256)),
            ],
        ),
    ]
