# Generated by Django 5.0 on 2024-07-16 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0004_timer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('created', models.DateField(verbose_name='creation date')),
                ('deadline', models.DateField(verbose_name='deadline')),
                ('priority', models.IntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calapp.task')),
            ],
        ),
    ]
