# Generated by Django 5.0 on 2024-07-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0005_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='updated',
            field=models.DateTimeField(verbose_name='timer last updated'),
        ),
    ]
