# Generated by Django 5.0 on 2024-07-18 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0006_alter_timer_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calapp.appointment'),
        ),
    ]
