# Generated by Django 5.0 on 2024-07-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0007_task_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
