# Generated by Django 5.0 on 2024-08-18 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calapp', '0008_timer_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='timer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calapp.timer'),
        ),
    ]
